### ISSUE TITLE
Kernel Swap Limit Error on container build on Unraid

### ISSUE THREAD

**Issue by cpsmith516** [pallebone/UnifiUnraidReborn#3] opened 2023-12-07 19:47 UTC
docker run
  -d
  --name='unifi-controller-reborn'
  --net='br0.4'
  --ip='192.168.4.100'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unraid"
  -e HOST_CONTAINERNAME="unifi-controller-reborn"
  -e 'TCP_PORT_8443'='8443'
  -e 'UDP_PORT_3478'='3478'
  -e 'UDP_PORT_10001'='10001'
  -e 'TCP_PORT_8080'='8080'
  -e 'UDP_PORT_1900'='1900'
  -e 'TCP_PORT_8843'='8843'
  -e 'TCP_PORT_8880'='8880'
  -e 'TCP_PORT_6789'='6789'
  -e 'UDP_PORT_5514'='5514'
  -e 'MEM_LIMIT'='4096'
  -e 'MEM_STARTUP'='2048'
  -e 'UMASK'='002'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:8443]'
  -l net.unraid.docker.icon='https://user-images.githubusercontent.com/11403137/277435263-1b01facd-1b15-4ba7-9495-e709c291d67f.jpg'
  -v '/mnt/user/appdata/unifi':'/unifi/var':'rw'
  --memory=8G '11notes/unifi:7.5.187-unraid'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
5e81912afffd7fb8684f181ab505931db9a75d489acf261efd8b0d409111cf72

The command finished successfully!

**Comment by pallebone** [comment] 2023-12-07 19:51
This is because Unraid does not support swap so the error is informational, and you must know to allocate enough ram for the docker image to run correctly. Ie if you are used to setting 4GB ram and 2GB swap you must set 6GB ram on unraid. 

Hope this helps :)

Closing as not an error/cannot be changed/how unraid works(unraid has no swap by design)

**Closed as completed by pallebone** 2023-12-07 19:51 UTC
